#!/usr/bin/env bash
# deploy/private-server/setup.sh
# ─────────────────────────────────────────────────────────────────────────────
# DevLab Private Server Setup — One script to configure everything:
#   • Ollama (model server)
#   • DevLab agent server
#   • Nginx (HTTPS reverse proxy)
#   • Systemd services (auto-start on reboot)
#   • Firewall rules
#
# Usage:
#   bash setup.sh --domain model.yourcompany.com --model codellama:34b --key YOUR_API_KEY
#
# Requirements:
#   • Ubuntu 22.04 or 24.04
#   • Root or sudo access
#   • Domain pointed to this server's IP (for HTTPS)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────────────
DOMAIN=""
MODEL="codellama:34b"
API_KEY=""
DEVLAB_PORT=4321
OLLAMA_PORT=11434
DEVLAB_DIR="/opt/devlab"
NODE_VERSION="20"

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) DOMAIN="$2"; shift 2 ;;
    --model)  MODEL="$2";  shift 2 ;;
    --key)    API_KEY="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [[ -z "$DOMAIN" || -z "$API_KEY" ]]; then
  echo ""
  echo "Usage: bash setup.sh --domain model.yourcompany.com --model codellama:34b --key YOUR_SECRET_KEY"
  echo ""
  exit 1
fi

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[DONE]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
step()    { echo -e "\n${CYAN}━━━ Step $1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; }

echo ""
echo -e "${CYAN}  DevLab Private Server Setup${NC}"
echo -e "${CYAN}  ════════════════════════════${NC}"
echo -e "  Domain : ${DOMAIN}"
echo -e "  Model  : ${MODEL}"
echo ""

# ── Step 1: System packages ───────────────────────────────────────────────────
step "1: Install system packages"
apt-get update -qq
apt-get install -y -qq curl nginx certbot python3-certbot-nginx ufw git
success "System packages installed"

# ── Step 2: Node.js ───────────────────────────────────────────────────────────
step "2: Install Node.js ${NODE_VERSION}"
if ! command -v node &>/dev/null || [[ $(node -e "process.stdout.write(process.versions.node.split('.')[0])") -lt 20 ]]; then
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | bash -
  apt-get install -y nodejs
fi
success "Node.js $(node --version) ready"

# ── Step 3: Ollama ────────────────────────────────────────────────────────────
step "3: Install Ollama"
if ! command -v ollama &>/dev/null; then
  curl -fsSL https://ollama.com/install.sh | sh
fi

# Configure Ollama to bind ONLY on localhost (Nginx proxies it — never expose directly)
mkdir -p /etc/systemd/system/ollama.service.d
cat > /etc/systemd/system/ollama.service.d/override.conf << EOF
[Service]
Environment="OLLAMA_HOST=127.0.0.1:${OLLAMA_PORT}"
Environment="OLLAMA_ORIGINS=*"
EOF

systemctl daemon-reload
systemctl enable ollama
systemctl restart ollama
sleep 3
success "Ollama installed and running on 127.0.0.1:${OLLAMA_PORT}"

# ── Step 4: Pull model ────────────────────────────────────────────────────────
step "4: Pull model: ${MODEL}"
info "This may take 10-30 minutes for large models..."
ollama pull "$MODEL"
success "Model ${MODEL} ready"

# ── Step 5: Install DevLab ────────────────────────────────────────────────────
step "5: Install DevLab"
if [[ ! -d "$DEVLAB_DIR" ]]; then
  info "DevLab not found at $DEVLAB_DIR"
  info "Copy your built DevLab binary or source to $DEVLAB_DIR"
  info "If you have the source: git clone <your-repo> $DEVLAB_DIR"
  mkdir -p "$DEVLAB_DIR"
fi

# If source is present, install deps
if [[ -f "$DEVLAB_DIR/package.json" ]]; then
  cd "$DEVLAB_DIR"
  npm install --omit=dev --silent
  npm link --silent
  success "DevLab installed from source"
elif [[ -f "$DEVLAB_DIR/devlab" ]]; then
  # Binary mode
  chmod +x "$DEVLAB_DIR/devlab"
  ln -sf "$DEVLAB_DIR/devlab" /usr/local/bin/devlab
  success "DevLab binary linked"
else
  warn "DevLab not found at $DEVLAB_DIR — install it manually after this script"
fi

# ── Step 6: Configure .env ────────────────────────────────────────────────────
step "6: Configure DevLab environment"
cat > "$DEVLAB_DIR/.env" << EOF
# DevLab Private Server Configuration
# Generated by setup.sh on $(date)

MODEL_PROVIDER=ollama
OPENAI_COMPAT_BASE_URL=http://127.0.0.1:${OLLAMA_PORT}
OPENAI_COMPAT_MODEL=${MODEL}
OPENAI_COMPAT_API_KEY=

# Protect the DevLab API — clients must send this key
DEVLAB_API_KEY=${API_KEY}

# Bind to all interfaces (Nginx handles SSL in front)
DEVLAB_HOST=0.0.0.0
UI_PORT=${DEVLAB_PORT}

# PRIVACY: Never store client prompts, code, or responses on this server.
# All inference is done in-memory only — source code stays on client machines.
DEVLAB_NO_LOG=1

SAFETY_MODE=normal
EOF
success ".env configured"

# ── Step 7: Systemd service for DevLab ───────────────────────────────────────
step "7: Create DevLab systemd service"
DEVLAB_BIN=$(command -v devlab 2>/dev/null || echo "node $DEVLAB_DIR/index.js")

cat > /etc/systemd/system/devlab.service << EOF
[Unit]
Description=DevLab Agent Server
After=network.target ollama.service
Wants=ollama.service

[Service]
Type=simple
User=root
WorkingDirectory=${DEVLAB_DIR}
EnvironmentFile=${DEVLAB_DIR}/.env
ExecStart=${DEVLAB_BIN} serve ${DEVLAB_DIR} --no-open --port ${DEVLAB_PORT}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable devlab
systemctl start devlab
sleep 3
success "DevLab service started"

# ── Step 8: Nginx config ──────────────────────────────────────────────────────
step "8: Configure Nginx reverse proxy"
cat > "/etc/nginx/sites-available/${DOMAIN}" << EOF
# DevLab private server — Nginx reverse proxy
# Handles HTTPS termination, forwards to DevLab (:${DEVLAB_PORT}) and Ollama (:${OLLAMA_PORT})

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

# Main HTTPS server
server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # SSL (certbot will fill these in)
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header Strict-Transport-Security "max-age=31536000" always;

    # ── DevLab Agent API (/api/* and /v1/* and WebSocket) ──────────────────
    location / {
        proxy_pass         http://127.0.0.1:${DEVLAB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 10m;
    }

    # ── Ollama Model API (/ollama/*) — proxied with auth strip ─────────────
    location /ollama/ {
        # Only DevLab server reaches here directly
        # Clients go through DevLab, not directly to Ollama
        allow 127.0.0.1;
        deny all;
        proxy_pass http://127.0.0.1:${OLLAMA_PORT}/;
        proxy_read_timeout 300s;
    }
}
EOF

ln -sf "/etc/nginx/sites-available/${DOMAIN}" "/etc/nginx/sites-enabled/${DOMAIN}"
rm -f /etc/nginx/sites-enabled/default
nginx -t
success "Nginx configured"

# ── Step 9: SSL certificate ───────────────────────────────────────────────────
step "9: Get SSL certificate (Let's Encrypt)"
systemctl start nginx
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
  --register-unsafely-without-email --redirect || {
  warn "Certbot failed — domain may not be pointing to this server yet"
  warn "Run manually: certbot --nginx -d ${DOMAIN}"
}
success "SSL certificate installed"

# ── Step 10: Firewall ─────────────────────────────────────────────────────────
step "10: Configure firewall"
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh        # keep SSH open!
ufw allow 80/tcp     # HTTP (redirects to HTTPS)
ufw allow 443/tcp    # HTTPS
# Ollama and DevLab raw ports are NOT exposed — Nginx only
ufw --force enable
success "Firewall configured (only 22, 80, 443 open)"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}  ✅ DevLab Private Server Ready!${NC}"
echo ""
echo -e "  🌐 Server URL : ${CYAN}https://${DOMAIN}${NC}"
echo -e "  🔑 API Key    : ${YELLOW}${API_KEY}${NC}  ← give this to clients"
echo -e "  🤖 Model      : ${MODEL}"
echo ""
echo -e "  Client app settings:"
echo -e "    Server URL : https://${DOMAIN}"
echo -e "    API Key    : ${API_KEY}"
echo ""
echo -e "  Useful commands:"
echo -e "    systemctl status devlab     # check agent status"
echo -e "    systemctl status ollama     # check model status"
echo -e "    journalctl -u devlab -f     # live logs"
echo -e "    ollama list                 # list models"
echo ""
