// diagram.js — PlantUML / Mermaid diagram generation
// Types: flowchart, sequence, class, architecture, component, er, state
// Architecture/class diagrams can be auto-generated by scanning a project.

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, extname, basename, dirname } from 'path';
import zlib from 'zlib';

export const DIAGRAM_TYPES = ['flowchart', 'sequence', 'class', 'architecture', 'component', 'er', 'state'];
export const DIAGRAM_FORMATS = ['plantuml', 'mermaid'];

/* ---------------- PlantUML server URL encoding ---------------- */

const PUML_ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_';

function plantumlEncode(text) {
  const deflated = zlib.deflateRawSync(Buffer.from(text, 'utf8'), { level: 9 });
  let out = '';
  for (let i = 0; i < deflated.length; i += 3) {
    const b1 = deflated[i], b2 = i + 1 < deflated.length ? deflated[i + 1] : 0, b3 = i + 2 < deflated.length ? deflated[i + 2] : 0;
    out += PUML_ALPHABET[b1 >> 2];
    out += PUML_ALPHABET[((b1 & 0x3) << 4) | (b2 >> 4)];
    out += PUML_ALPHABET[((b2 & 0xF) << 2) | (b3 >> 6)];
    out += PUML_ALPHABET[b3 & 0x3F];
  }
  return out;
}

export function plantumlUrl(pumlText, imageFormat = 'svg') {
  return `https://www.plantuml.com/plantuml/${imageFormat}/${plantumlEncode(pumlText)}`;
}

export function mermaidLiveUrl(mmdText) {
  const payload = JSON.stringify({ code: mmdText, mermaid: { theme: 'default' } });
  return `https://mermaid.live/edit#base64:${Buffer.from(payload, 'utf8').toString('base64')}`;
}

/* ---------------- Project scanning (architecture / class) ---------------- */

const SOURCE_EXTS = new Set(['.js', '.mjs', '.cjs', '.ts', '.tsx', '.jsx', '.swift', '.kt', '.kts', '.java', '.dart', '.py', '.go', '.cs', '.rs']);
const SKIP_DIRS = new Set(['node_modules', '.git', 'build', 'dist', '.build', 'DerivedData', 'Pods', '.gradle', '.dart_tool', '__pycache__', 'target', 'bin', 'obj', '.idea', '.vscode', 'coverage']);

function walkSources(dir, maxFiles = 400, files = [], depth = 0) {
  if (depth > 6 || files.length >= maxFiles) return files;
  let entries;
  try { entries = readdirSync(dir); } catch { return files; }
  for (const e of entries) {
    if (files.length >= maxFiles) break;
    if (SKIP_DIRS.has(e) || e.startsWith('.')) continue;
    const p = join(dir, e);
    let st;
    try { st = statSync(p); } catch { continue; }
    if (st.isDirectory()) walkSources(p, maxFiles, files, depth + 1);
    else if (SOURCE_EXTS.has(extname(e))) files.push(p);
  }
  return files;
}

// Group source files into "modules" (top-level dirs under src/ or project root)
function moduleOf(projectPath, file) {
  const rel = file.slice(projectPath.length + 1);
  const parts = rel.split('/');
  if (parts[0] === 'src' && parts.length > 2) return parts[1];
  if (parts.length > 1) return parts[0];
  return '(root)';
}

export function analyzeArchitecture(projectPath) {
  const files = walkSources(projectPath);
  const modules = new Map(); // name -> { files: n }
  const edges = new Map();   // "from->to" -> count

  const fileToModule = new Map();
  for (const f of files) {
    const m = moduleOf(projectPath, f);
    fileToModule.set(f, m);
    modules.set(m, (modules.get(m) || 0) + 1);
  }

  const importRe = /(?:import\s+.*?from\s+['"]([^'"]+)['"]|require\(\s*['"]([^'"]+)['"]\s*\)|^import\s+([A-Za-z0-9_.]+)|^from\s+(\S+)\s+import)/gm;

  for (const f of files) {
    let src;
    try { src = readFileSync(f, 'utf8'); } catch { continue; }
    const fromMod = fileToModule.get(f);
    let m;
    while ((m = importRe.exec(src)) !== null) {
      const spec = m[1] || m[2] || m[3] || m[4];
      if (!spec || !spec.startsWith('.')) continue; // local imports only
      const target = join(dirname(f), spec);
      // resolve to a module by matching known files loosely
      for (const [otherFile, otherMod] of fileToModule) {
        if (otherMod === fromMod) continue;
        if (otherFile.startsWith(target) || target.startsWith(otherFile.replace(extname(otherFile), ''))) {
          const key = `${fromMod}->${otherMod}`;
          edges.set(key, (edges.get(key) || 0) + 1);
          break;
        }
      }
    }
  }

  // External deps from package.json / pubspec / gradle
  const external = [];
  try {
    const pkg = JSON.parse(readFileSync(join(projectPath, 'package.json'), 'utf8'));
    external.push(...Object.keys(pkg.dependencies || {}).slice(0, 8));
  } catch { /* not a node project */ }

  return {
    modules: [...modules.entries()].map(([name, fileCount]) => ({ name, fileCount })),
    edges: [...edges.entries()].map(([k, count]) => { const [from, to] = k.split('->'); return { from, to, count }; }),
    external,
    totalFiles: files.length,
  };
}

const CLASS_RES = {
  '.swift': /(?:class|struct|protocol|enum|actor)\s+([A-Z]\w+)/g,
  '.kt': /(?:class|interface|object|enum class)\s+([A-Z]\w+)/g,
  '.java': /(?:class|interface|enum)\s+([A-Z]\w+)/g,
  '.ts': /(?:class|interface)\s+([A-Z]\w+)/g,
  '.js': /class\s+([A-Z]\w+)/g,
  '.dart': /(?:class|mixin)\s+([A-Z]\w+)/g,
  '.py': /class\s+([A-Z]\w+)/g,
  '.cs': /(?:class|interface|record)\s+([A-Z]\w+)/g,
};

export function analyzeClasses(projectPath, maxClasses = 40) {
  const files = walkSources(projectPath);
  const classes = []; // { name, file, extends }
  for (const f of files) {
    const re = CLASS_RES[extname(f)] || CLASS_RES[extname(f) === '.tsx' ? '.ts' : null];
    if (!re) continue;
    let src;
    try { src = readFileSync(f, 'utf8'); } catch { continue; }
    let m;
    const localRe = new RegExp(re.source, 'g');
    while ((m = localRe.exec(src)) !== null && classes.length < maxClasses) {
      const name = m[1];
      // crude inheritance capture: "class Foo: Bar" / "class Foo extends Bar"
      const tail = src.slice(m.index, m.index + 150);
      const inh = tail.match(new RegExp(`${name}\\s*(?::|extends|implements)\\s*([A-Z]\\w+)`));
      classes.push({ name, file: basename(f), parent: inh ? inh[1] : null });
    }
    if (classes.length >= maxClasses) break;
  }
  return classes;
}

/* ---------------- Diagram body builders ---------------- */

const sanitize = (s) => String(s).replace(/[^A-Za-z0-9_]/g, '_');

function buildArchitecture(arch, format, title) {
  if (format === 'mermaid') {
    const lines = ['graph TD'];
    for (const mod of arch.modules) lines.push(`  ${sanitize(mod.name)}["${mod.name} (${mod.fileCount} files)"]`);
    for (const e of arch.edges) lines.push(`  ${sanitize(e.from)} -->|${e.count}| ${sanitize(e.to)}`);
    if (arch.external.length) {
      lines.push(`  EXT[("external: ${arch.external.slice(0, 5).join(', ')}")]`);
    }
    return lines.join('\n');
  }
  const lines = ['@startuml', `title ${title}`, 'skinparam componentStyle rectangle'];
  for (const mod of arch.modules) lines.push(`component "${mod.name}\\n(${mod.fileCount} files)" as ${sanitize(mod.name)}`);
  for (const e of arch.edges) lines.push(`${sanitize(e.from)} --> ${sanitize(e.to)} : ${e.count} refs`);
  if (arch.external.length) {
    lines.push(`cloud "External deps" as EXT`);
    lines.push(`note right of EXT : ${arch.external.slice(0, 8).join('\\n')}`);
  }
  lines.push('@enduml');
  return lines.join('\n');
}

function buildClassDiagram(classes, format, title) {
  if (format === 'mermaid') {
    const lines = ['classDiagram'];
    for (const c of classes) {
      lines.push(`  class ${sanitize(c.name)}`);
      if (c.parent) lines.push(`  ${sanitize(c.parent)} <|-- ${sanitize(c.name)}`);
    }
    return lines.join('\n');
  }
  const lines = ['@startuml', `title ${title}`];
  for (const c of classes) {
    lines.push(`class ${sanitize(c.name)} <<${c.file}>>`);
    if (c.parent) lines.push(`${sanitize(c.parent)} <|-- ${sanitize(c.name)}`);
  }
  lines.push('@enduml');
  return lines.join('\n');
}

// steps: ["A -> B: message", ...] or nodes/edges for flowchart
function buildFromSteps(type, steps, format, title) {
  if (format === 'mermaid') {
    if (type === 'sequence') {
      const lines = ['sequenceDiagram'];
      for (const s of steps) {
        const m = s.match(/^(.+?)\s*->\s*(.+?)\s*:\s*(.*)$/);
        lines.push(m ? `  ${sanitize(m[1])}->>${sanitize(m[2])}: ${m[3]}` : `  Note over A: ${s}`);
      }
      return lines.join('\n');
    }
    if (type === 'state') {
      const lines = ['stateDiagram-v2'];
      for (const s of steps) {
        const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
        if (m) lines.push(`  ${sanitize(m[1])} --> ${sanitize(m[2])}${m[3] ? ` : ${m[3]}` : ''}`);
      }
      return lines.join('\n');
    }
    if (type === 'er') {
      const lines = ['erDiagram'];
      for (const s of steps) {
        const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
        if (m) lines.push(`  ${sanitize(m[1])} ||--o{ ${sanitize(m[2])} : "${m[3] || 'has'}"`);
      }
      return lines.join('\n');
    }
    // flowchart / component default
    const lines = ['graph TD'];
    for (const s of steps) {
      const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
      lines.push(m ? `  ${sanitize(m[1])}["${m[1]}"] -->${m[3] ? `|${m[3]}|` : ''} ${sanitize(m[2])}["${m[2]}"]` : `  ${sanitize(s)}["${s}"]`);
    }
    return lines.join('\n');
  }

  // PlantUML
  const lines = ['@startuml', `title ${title}`];
  if (type === 'sequence') {
    for (const s of steps) {
      const m = s.match(/^(.+?)\s*->\s*(.+?)\s*:\s*(.*)$/);
      lines.push(m ? `"${m[1]}" -> "${m[2]}" : ${m[3]}` : `note over "${s}"`);
    }
  } else if (type === 'state') {
    for (const s of steps) {
      const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
      if (m) lines.push(`${sanitize(m[1])} --> ${sanitize(m[2])}${m[3] ? ` : ${m[3]}` : ''}`);
    }
  } else if (type === 'er') {
    for (const s of steps) {
      const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
      if (m) {
        lines.push(`entity ${sanitize(m[1])}`, `entity ${sanitize(m[2])}`, `${sanitize(m[1])} ||--o{ ${sanitize(m[2])} : ${m[3] || 'has'}`);
      }
    }
  } else if (type === 'component') {
    lines.push('skinparam componentStyle rectangle');
    for (const s of steps) {
      const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
      if (m) lines.push(`[${m[1]}] --> [${m[2]}]${m[3] ? ` : ${m[3]}` : ''}`);
      else lines.push(`[${s}]`);
    }
  } else {
    // flowchart via activity-ish arrows
    for (const s of steps) {
      const m = s.match(/^(.+?)\s*->\s*(.+?)(?:\s*:\s*(.*))?$/);
      if (m) lines.push(`rectangle "${m[1]}" as ${sanitize(m[1])}`, `rectangle "${m[2]}" as ${sanitize(m[2])}`, `${sanitize(m[1])} --> ${sanitize(m[2])}${m[3] ? ` : ${m[3]}` : ''}`);
      else lines.push(`rectangle "${s}"`);
    }
    // de-dup rectangle declarations
    const seen = new Set();
    return lines.filter(l => {
      if (!l.startsWith('rectangle')) return true;
      if (seen.has(l)) return false;
      seen.add(l);
      return true;
    }).concat('@enduml').join('\n');
  }
  lines.push('@enduml');
  return lines.join('\n');
}

/* ---------------- Main entry ---------------- */

/**
 * generateDiagram(options)
 *  type:        flowchart | sequence | class | architecture | component | er | state (default: flowchart)
 *  format:      plantuml | mermaid (default: plantuml)
 *  title:       diagram title
 *  steps:       array of "From -> To: label" strings (for flowchart/sequence/state/er/component)
 *  content:     raw diagram body — used verbatim if provided (advanced)
 *  projectPath: scan this project to auto-generate (architecture & class types)
 *  output:      file path to save (.puml/.mmd auto-appended if no extension)
 */
export function generateDiagram(options = {}) {
  const type = (options.type || 'flowchart').toLowerCase();
  const format = (options.format || 'plantuml').toLowerCase();
  const title = options.title || `${type} diagram`;

  if (!DIAGRAM_TYPES.includes(type)) return { error: `Unknown type '${type}'. Use: ${DIAGRAM_TYPES.join(', ')}` };
  if (!DIAGRAM_FORMATS.includes(format)) return { error: `Unknown format '${format}'. Use: ${DIAGRAM_FORMATS.join(', ')}` };

  let body;
  let meta = {};

  if (options.content) {
    body = format === 'plantuml' && !options.content.includes('@startuml')
      ? `@startuml\ntitle ${title}\n${options.content}\n@enduml`
      : options.content;
  } else if (type === 'architecture' || (type === 'component' && options.projectPath)) {
    if (!options.projectPath && !options.steps) return { error: 'architecture type needs projectPath (to scan) or steps' };
    if (options.projectPath) {
      const arch = analyzeArchitecture(options.projectPath);
      body = buildArchitecture(arch, format, title);
      meta = { modules: arch.modules.length, edges: arch.edges.length, scannedFiles: arch.totalFiles };
    } else {
      body = buildFromSteps(type, options.steps, format, title);
    }
  } else if (type === 'class' && options.projectPath) {
    const classes = analyzeClasses(options.projectPath);
    if (!classes.length) return { error: `No classes found in ${options.projectPath}` };
    body = buildClassDiagram(classes, format, title);
    meta = { classes: classes.length };
  } else {
    if (!options.steps || !options.steps.length) {
      return { error: `type '${type}' needs 'steps' (["A -> B: label", ...])${type === 'class' || type === 'architecture' ? " or 'projectPath'" : ''}` };
    }
    body = type === 'class'
      ? buildClassDiagram(options.steps.map(s => { const m = s.match(/^(.+?)\s*->\s*(.+?)$/); return m ? { name: m[2].trim(), parent: m[1].trim(), file: '' } : { name: s, parent: null, file: '' }; }), format, title)
      : buildFromSteps(type, options.steps, format, title);
  }

  const result = { type, format, title, diagram: body, ...meta };

  if (format === 'plantuml') {
    result.previewUrl = plantumlUrl(body, 'svg');
    result.pngUrl = plantumlUrl(body, 'png');
  } else {
    result.previewUrl = mermaidLiveUrl(body);
  }

  if (options.output) {
    let out = options.output;
    if (!extname(out)) out += format === 'plantuml' ? '.puml' : '.mmd';
    try {
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, body, 'utf8');
      result.savedTo = out;
    } catch (e) {
      result.saveError = e.message;
    }
  }

  return result;
}
